services:
  - type: web
    name: zain-kb-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    preDeployCommand: npx prisma db push
    envVars:
      - key: DATABASE_URL
        sync: false
      - fromGroup: zain-kb-secrets

envVarGroups:
  - name: zain-kb-secrets
    envVars:
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
